name: Check
on:
  push:
    branches: ["main"]
    tags: [v0.*]
  pull_request:

jobs:
  test-msrv:
    name: Test MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "1.70.0"
          override: true
      - uses: actions-rs/cargo@v1
        name: Main check
        with:
          command: check
          args: --workspace
      - uses: actions-rs/cargo@v1
        name: Bench compile check
        with:
          command: bench
          args: --no-run
  test:
    name: Test Nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        name: Default test
        with:
          command: test
      - uses: actions-rs/cargo@v1
        name: Test all
        with:
          command: test
          args: --workspace
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - name: run rustfmt
        run: |
          cargo fmt -- --check
